In [1]:
# 1. Use beutifulsoup to 
# 2. Confirm loaded correctly
# 3. define def to find the table
# what does it return the table as? 

import pandas as pd
from bs4 import BeautifulSoup as bs

def getTables(htmlDoc):
	with open(htmlDoc) as fp:
		soup = bs(fp)
	return soup.findAll('table')
	
course_hist = getTables('course_history.html')

print(course_hist)

[<table width="800px"><tr><td colspan="2"><p>Undergraduate Credential Summary </p></td></tr><tr><td class="t1">Credential Awarded: </td><td>Bachelor of Arts</td></tr><tr><td class="t1">Plan: </td><td>Specialization Pure and Applied Mathematics</td></tr><tr><td class="t1">Confer Date: </td><td>05/10/2018</td></tr><tr><td class="t1">Final Graduation GPA: </td><td> 3.21</td></tr><tr><td colspan="2"></td></tr><tr><td colspan="2"><p>Undergraduate Academic Program History </p></td></tr><tr><td colspan="2"></td></tr><tr><td class="t1">Active in Program</td><td>26/08/2015</td></tr><tr><td class="t1">Admit Term </td><td>Fall 2015</td></tr><tr><td class="t1"> </td><td>Matriculated</td></tr><tr><td class="t1"> </td><td>Bachelor of Arts</td></tr><tr><td class="t1"> </td><td>Major Mathematics and Statistics</td></tr><tr><td colspan="2"></td></tr><tr><td class="t1">Active in Program</td><td>30/11/2015</td></tr><tr><td class="t1"> </td><td>Concentration Change</td></tr><tr><td class="t1"> </td><td>Bachelor of Arts</td></tr><tr><td class="t1"> </td><td>Specialization Pure and Applied Mathematics</td></tr><tr><td colspan="2"></td></tr><tr><td class="t1">Completed Program</td><td>15/10/2018</td></tr><tr><td class="t1"> </td><td>Program Completed</td></tr><tr><td class="t1"> </td><td>Bachelor of Arts</td></tr><tr><td class="t1"> </td><td>Specialization Pure and Applied Mathematics</td></tr><tr><td class="t1">Min. Credits Required:</td><td>90.00</td></tr><tr><td class="t1">Program Credits Earned:</td><td>105.50</td></tr><tr><td class="t1">Cumulative GPA:</td><td> 3.21</td></tr><tr><td colspan="2"></td></tr><tr><td colspan="2"><p>Beginning of Undergraduate Record </p></td></tr><tr><td colspan="2"></td></tr><tr><td colspan="2"><b>Fall 2015</b></td></tr><tr><td colspan="2">Bachelor of Arts, Specialization Pure and Applied Mathematics</td></tr><tr><td class="crsTBH" colspan="3">Transfer Credits</td></tr><tr><td colspan="2"><table border="0" class="crsTB"><tr><th class="tc1" colspan="2">Course</th><th class="tc2">Description</th><th class="tc3">Grade</th><th class="tc4">Year Attended</th><th class="tc5">Program Credits Earned</th></tr><tr><td class="tc11">GENL</td><td class="tc12">    AB</td><td class="tc2">McGill University 1997-2002</td><td class="tc3">TRC</td><td class="tc4">2002</td><td class="tc5">30.00</td></tr></table></td></tr><tr><td colspan="2"> </td></tr><tr><td class="crsTBH" colspan="3">Transfer Credits</td></tr><tr><td colspan="2"><table border="0" class="crsTB"><tr><th class="tc1" colspan="2">Course</th><th class="tc2">Description</th><th class="tc3">Grade</th><th class="tc4">Year Attended</th><th class="tc5">Program Credits Earned</th></tr><tr><td class="tc11">MAST</td><td class="tc12"> 218</td><td class="tc2">Langara College 2003-05</td><td class="tc3">TRC</td><td class="tc4">2005</td><td class="tc5"> 3.00</td></tr><tr><td class="tc11">MAST</td><td class="tc12"> 234</td><td class="tc2">Langara College 2003-05</td><td class="tc3">TRC</td><td class="tc4">2005</td><td class="tc5"> 3.00</td></tr><tr><td class="tc11">MATH</td><td class="tc12"> 201</td><td class="tc2">Langara College 2003-05</td><td class="tc3">EX</td><td class="tc4">2005</td><td class="tc5"> 0.00</td></tr><tr><td class="tc11">MATH</td><td class="tc12"> 203</td><td class="tc2">Langara College 2003-05</td><td class="tc3">EX</td><td class="tc4">2005</td><td class="tc5"> 0.00</td></tr><tr><td class="tc11">MATH</td><td class="tc12"> 204</td><td class="tc2">Langara College 2003-05</td><td class="tc3">EX</td><td class="tc4">2005</td><td class="tc5"> 0.00</td></tr><tr><td class="tc11">MATH</td><td class="tc12"> 205</td><td class="tc2">Langara College 2003-05</td><td class="tc3">EX</td><td class="tc4">2005</td><td class="tc5"> 0.00</td></tr><tr><td class="tc11">MATH</td><td class="tc12"> 206</td><td class="tc2">Langara College 2003-05</td><td class="tc3">EX</td><td class="tc4">2005</td><td class="tc5"> 0.00</td></tr><tr><td class="tc11">MATH</td><td class="tc12"> 364</td><td class="tc2">Langara College 2003-05</td><td class="tc3">TRC</td><td class="tc4">2005</td><td class="tc5"> 3.00</td></tr><tr><td class="tc11">PHYS</td><td class="tc12"> 204</td><td class="tc2">Langara College 2003-05</td><td class="tc3">EX</td><td class="tc4">2005</td><td class="tc5"> 0.00</td></tr><tr><td class="tc11">PHYS</td><td class="tc12"> 224</td><td class="tc2">Langara College 2003-05</td><td class="tc3">EX</td><td class="tc4">2005</td><td class="tc5"> 0.00</td></tr></table></td></tr><tr><td colspan="2"> </td></tr><tr><td colspan="2"><table border="0" class="crsTB"><tr><th class="c1" colspan="3">Course</th><th class="c2">Description</th><th class="c3">Attempted</th><th class="c4">Grade</th><th class="c5">Notation</th><th class="c8">GPA</th><th class="c6">Class Avg</th><th class="c7">Class Size</th><th class="c9">Program Credits Earned</th><th class="c10">Other</th></tr><tr><td class="s1">FRAN</td><td class="s2"> 305</td><td class="s3">B</td><td class="G2">COMMUNICATION ORALE</td><td class="c3"> 3.00</td><td class="c4">B+</td><td class="c5"></td><td class="c8"> 3.30</td><td class="c6"> 3.12</td><td class="c7">26</td><td class="c9"> 3.00</td><td class="c10"></td></tr><tr><td class="s1">GEOL</td><td class="s2"> 210</td><td class="s3">X</td><td class="G2">INTRODUCTION TO THE EARTH</td><td class="c3"> 3.00</td><td class="c4">A-</td><td class="c5"></td><td class="c8"> 3.70</td><td class="c6"> 3.25</td><td class="c7">69</td><td class="c9"> 3.00</td><td class="c10"></td></tr><tr><td class="s1">MAST</td><td class="s2"> 217</td><td class="s3">A</td><td class="G2">INTRO/MATHEMATICAL THINKING</td><td class="c3"> 3.00</td><td class="c4">A+</td><td class="c5"></td><td class="c8"> 4.30</td><td class="c6"> 2.94</td><td class="c7">49</td><td class="c9"> 3.00</td><td class="c10"></td></tr><tr><td class="s1">MAST</td><td class="s2"> 219</td><td class="s3">A</td><td class="G2">MULTIVARIABLE CALCULUS II</td><td class="c3"> 3.00</td><td class="c4">C</td><td class="c5"></td><td class="c8"> 2.00</td><td class="c6"> 1.69</td><td class="c7">17</td><td class="c9"> 3.00</td><td class="c10"></td></tr><tr><td class="s1">MECH</td><td class="s2"> 211</td><td class="s3">Y</td><td class="G2">MECHANICAL ENGR. DRAWING</td><td class="c3"> 3.50</td><td class="c4">B-</td><td class="c5"></td><td class="c8"> 2.70</td><td class="c6"> 2.62</td><td class="c7">70</td><td class="c9"> 3.50</td><td class="c10"></td></tr></table></td></tr><tr><td colspan="2"> </td></tr><tr><td colspan="2">Term GPA        3.18</td></tr><tr><td colspan="2"> </td></tr><tr><td colspan="2"><b>Winter 2016</b></td></tr><tr><td colspan="2">Bachelor of Arts, Specialization Pure and Applied Mathematics</td></tr><tr><td colspan="2"><table border="0" class="crsTB"><tr><th class="c1" colspan="3">Course</th><th class="c2">Description</th><th class="c3">Attempted</th><th class="c4">Grade</th><th class="c5">Notation</th><th class="c8">GPA</th><th class="c6">Class Avg</th><th class="c7">Class Size</th><th class="c9">Program Credits Earned</th><th class="c10">Other</th></tr><tr><td class="s1">GEOL</td><td class="s2"> 208</td><td class="s3">AA</td><td class="G2">THE EARTH, MOON AND PLANETS</td><td class="c3"> 3.00</td><td class="c4">A-</td><td class="c5"></td><td class="c8"> 3.70</td><td class="c6"> 3.00</td><td class="c7">186</td><td class="c9"> 3.00</td><td class="c10"></td></tr><tr><td class="s1">MATH</td><td class="s2"> 252</td><td class="s3">A</td><td class="G2">LINEAR ALGEBRA II</td><td class="c3"> 3.00</td><td class="c4">D</td><td class="c5"></td><td class="c8"> </td><td class="c6"> 2.20</td><td class="c7">53</td><td class="c9"> 3.00</td><td class="c10">INIT</td></tr><tr><td class="s1">MATH</td><td class="s2"> 365</td><td class="s3">A</td><td class="G2">ANALYSIS II</td><td class="c3"> 3.00</td><td class="c4">B</td><td class="c5"></td><td class="c8"> 3.00</td><td class="c6"> 2.38</td><td class="c7">49</td><td class="c9"> 3.00</td><td class="c10"></td></tr><tr><td class="s1">STAT</td><td class="s2"> 249</td><td class="s3">BB</td><td class="G2">PROBABILITY I</td><td class="c3"> 3.00</td><td class="c4">B+</td><td class="c5"></td><td class="c8"> 3.30</td><td class="c6"> 2.59</td><td class="c7">32</td><td class="c9"> 3.00</td><td class="c10"></td></tr></table></td></tr><tr><td colspan="2"> </td></tr><tr><td colspan="2">Term GPA        3.33</td></tr><tr><td colspan="2"> </td></tr><tr class="crsTB"><td colspan="2">08/05/2017: ASSESSED: ACCEPTABLE STANDING</td></tr><tr class="crsTB"><td colspan="2">ASSESSMENT GPA:  2.99 - ASSESSMENT PERIOD: Fall 2015 - Winter 2016</td></tr><tr><td colspan="2"> </td></tr><tr><td colspan="2"><b>Fall 2016</b></td></tr><tr><td colspan="2">Bachelor of Arts, Specialization Pure and Applied Mathematics</td></tr><tr><td colspan="2"><table border="0" class="crsTB"><tr><th class="c1" colspan="3">Course</th><th class="c2">Description</th><th class="c3">Attempted</th><th class="c4">Grade</th><th class="c5">Notation</th><th class="c8">GPA</th><th class="c6">Class Avg</th><th class="c7">Class Size</th><th class="c9">Program Credits Earned</th><th class="c10">Other</th></tr><tr><td class="s1">MATH</td><td class="s2"> 366</td><td class="s3">AA</td><td class="G2">COMPLEX ANALYSIS I</td><td class="c3"> 3.00</td><td class="c4">A-</td><td class="c5"></td><td class="c8"> 3.70</td><td class="c6"> 2.45</td><td class="c7">17</td><td class="c9"> 3.00</td><td class="c10"></td></tr><tr><td class="s1">MATH</td><td class="s2"> 369</td><td class="s3">A</td><td class="G2">ABSTRACT ALGEBRA I</td><td class="c3"> 3.00</td><td class="c4">B-</td><td class="c5"></td><td class="c8"> 2.70</td><td class="c6"> 2.52</td><td class="c7">18</td><td class="c9"> 3.00</td><td class="c10"></td></tr><tr><td class="s1">MATH</td><td class="s2"> 392</td><td class="s3">A</td><td class="G2">ELEMENTARY NUMBER THEORY</td><td class="c3"> 3.00</td><td class="c4">A</td><td class="c5"></td><td class="c8"> 4.00</td><td class="c6"> 2.35</td><td class="c7">13</td><td class="c9"> 3.00</td><td class="c10"></td></tr><tr><td class="s1">MATH</td><td class="s2"> 475</td><td class="s3">A</td><td class="G2">DISCRETE DYN.SYS,CHAOS&amp;FRACT</td><td class="c3"> 3.00</td><td class="c4">A-</td><td class="c5"></td><td class="c8"> 3.70</td><td class="c6"></td><td class="c7"></td><td class="c9"> 3.00</td><td class="c10"></td></tr><tr><td class="c1" colspan="3">Course Topic:</td><td>DISCRETE DYNAMICAL SYSTEMS</td></tr></table></td></tr><tr><td colspan="2"> </td></tr><tr><td colspan="2">Term GPA        3.53</td></tr><tr><td colspan="2"> </td></tr><tr><td colspan="2"><b>Winter 2017</b></td></tr><tr><td colspan="2">Bachelor of Arts, Specialization Pure and Applied Mathematics</td></tr><tr><td colspan="2"><table border="0" class="crsTB"><tr><th class="c1" colspan="3">Course</th><th class="c2">Description</th><th class="c3">Attempted</th><th class="c4">Grade</th><th class="c5">Notation</th><th class="c8">GPA</th><th class="c6">Class Avg</th><th class="c7">Class Size</th><th class="c9">Program Credits Earned</th><th class="c10">Other</th></tr><tr><td class="s1">MATH</td><td class="s2"> 252</td><td class="s3">AA</td><td class="G2">LINEAR ALGEBRA II</td><td class="c3"> 3.00</td><td class="c4">C</td><td class="c5"></td><td class="c8"> 2.00</td><td class="c6"> 2.40</td><td class="c7">58</td><td class="c9"> 0.00</td><td class="c10">REPT</td></tr><tr><td class="s1">MATH</td><td class="s2"> 467</td><td class="s3">A</td><td class="G2">MEASURE THEORY</td><td class="c3"> 3.00</td><td class="c4">B</td><td class="c5"></td><td class="c8"> 3.00</td><td class="c6"> 2.86</td><td class="c7">11</td><td class="c9"> 3.00</td><td class="c10"></td></tr><tr><td class="s1">MATH</td><td class="s2"> 470</td><td class="s3">C</td><td class="G2">ABSTRACT ALGEBRA II</td><td class="c3"> 3.00</td><td class="c4">A</td><td class="c5"></td><td class="c8"> 4.00</td><td class="c6"> 3.23</td><td class="c7">13</td><td class="c9"> 3.00</td><td class="c10"></td></tr><tr><td class="s1">MATH</td><td class="s2"> 494</td><td class="s3">E</td><td class="G2">TOPICS/PURE &amp; APPLIED MATH</td><td class="c3"> 3.00</td><td class="c4">B</td><td class="c5"></td><td class="c8"> 3.00</td><td class="c6"></td><td class="c7"></td><td class="c9"> 3.00</td><td class="c10"></td></tr><tr><td class="c1" colspan="3">Course Topic:</td><td>SET THEORY</td></tr></table></td></tr><tr><td colspan="2"> </td></tr><tr><td colspan="2">Term GPA        3.00</td></tr><tr><td colspan="2"> </td></tr><tr class="crsTB"><td colspan="2">24/05/2017: ASSESSED: ACCEPTABLE STANDING</td></tr><tr class="crsTB"><td colspan="2">ASSESSMENT GPA:  3.26 - ASSESSMENT PERIOD: Fall 2016 - Winter 2017</td></tr><tr><td colspan="2"> </td></tr><tr><td colspan="2"><b>Fall 2017</b></td></tr><tr><td colspan="2">Bachelor of Arts, Specialization Pure and Applied Mathematics</td></tr><tr><td colspan="2"><table border="0" class="crsTB"><tr><th class="c1" colspan="3">Course</th><th class="c2">Description</th><th class="c3">Attempted</th><th class="c4">Grade</th><th class="c5">Notation</th><th class="c8">GPA</th><th class="c6">Class Avg</th><th class="c7">Class Size</th><th class="c9">Program Credits Earned</th><th class="c10">Other</th></tr><tr><td class="s1">MATH</td><td class="s2"> 354</td><td class="s3">A</td><td class="G2">NUMERICAL ANALYSIS</td><td class="c3"> 3.00</td><td class="c4">B+</td><td class="c5"></td><td class="c8"> 3.30</td><td class="c6"> 3.40</td><td class="c7">51</td><td class="c9"> 3.00</td><td class="c10"></td></tr><tr><td class="s1">MATH</td><td class="s2"> 370</td><td class="s3">A</td><td class="G2">ORDINARY DIFFERENTIAL EQUAT.</td><td class="c3"> 3.00</td><td class="c4">B-</td><td class="c5"></td><td class="c8"> 2.70</td><td class="c6"> 3.01</td><td class="c7">44</td><td class="c9"> 3.00</td><td class="c10"></td></tr><tr><td class="s1">MATH</td><td class="s2"> 464</td><td class="s3">B</td><td class="G2">REAL ANALYSIS</td><td class="c3"> 3.00</td><td class="c4">B+</td><td class="c5"></td><td class="c8"> 3.30</td><td class="c6"> 2.65</td><td class="c7">21</td><td class="c9"> 3.00</td><td class="c10"></td></tr><tr><td class="s1">MATH</td><td class="s2"> 494</td><td class="s3">A</td><td class="G2">TOPICS/PURE &amp; APPLIED MATH</td><td class="c3"> 3.00</td><td class="c4">B-</td><td class="c5"></td><td class="c8"> 2.70</td><td class="c6"></td><td class="c7"></td><td class="c9"> 3.00</td><td class="c10"></td></tr><tr><td class="c1" colspan="3">Course Topic:</td><td>ALGEBRAIC NUMBER THEORY</td></tr></table></td></tr><tr><td colspan="2"> </td></tr><tr><td colspan="2">Term GPA        3.00</td></tr><tr><td colspan="2"> </td></tr><tr><td colspan="2"><b>Winter 2018</b></td></tr><tr><td colspan="2">Bachelor of Arts, Specialization Pure and Applied Mathematics</td></tr><tr><td colspan="2"><table border="0" class="crsTB"><tr><th class="c1" colspan="3">Course</th><th class="c2">Description</th><th class="c3">Attempted</th><th class="c4">Grade</th><th class="c5">Notation</th><th class="c8">GPA</th><th class="c6">Class Avg</th><th class="c7">Class Size</th><th class="c9">Program Credits Earned</th><th class="c10">Other</th></tr><tr><td class="s1">INTU</td><td class="s2">    MJKY</td><td class="s3">IU</td><td class="G2">HONOURS ALGEBRA 4</td><td class="c3"> 3.00</td><td class="c4">C+</td><td class="c5"></td><td class="c8"> 2.30</td><td class="c6"></td><td class="c7"></td><td class="c9"> 3.00</td><td class="c10"></td></tr><tr><td class="c1" colspan="3">Course Topic:</td><td>MATH 457 MCGILL</td></tr><tr><td class="s1">MATH</td><td class="s2"> 494</td><td class="s3">B</td><td class="G2">TOPICS/PURE &amp; APPLIED MATH</td><td class="c3"> 3.00</td><td class="c4">A+</td><td class="c5"></td><td class="c8"> 4.30</td><td class="c6"></td><td class="c7"></td><td class="c9"> 3.00</td><td class="c10"></td></tr><tr><td class="c1" colspan="3">Course Topic:</td><td>RANDOM MATRICES</td></tr></table></td></tr><tr><td colspan="2"> </td></tr><tr><td colspan="2">Term GPA        3.30</td></tr><tr><td colspan="2"> </td></tr><tr class="crsTB"><td colspan="2">05/10/2018: ASSESSED: ACCEPTABLE STANDING</td></tr><tr class="crsTB"><td colspan="2">ASSESSMENT GPA:  3.18 - ASSESSMENT PERIOD: Fall 2017 - Winter 2018</td></tr><tr><td colspan="2"> </td></tr><tr><td colspan="2"><br/></td></tr><tr><td colspan="2"><br/></td></tr><tr><td class="footer" colspan="2">End of Student Record</td></tr><tr><td colspan="2"><hr/><br/></td></tr><tr><td class="footer" colspan="2">This is not an official transcript</td></tr><tr><td class="footer" colspan="2">A term GPA can change due to a subsequent course repeat</td></tr><tr><td class="footer" colspan="2">Date of Issue: 16/02/2019</td></tr></table>, <table border="0" class="crsTB"><tr><th class="tc1" colspan="2">Course</th><th class="tc2">Description</th><th class="tc3">Grade</th><th class="tc4">Year Attended</th><th class="tc5">Program Credits Earned</th></tr><tr><td class="tc11">GENL</td><td class="tc12">    AB</td><td class="tc2">McGill University 1997-2002</td><td class="tc3">TRC</td><td class="tc4">2002</td><td class="tc5">30.00</td></tr></table>, <table border="0" class="crsTB"><tr><th class="tc1" colspan="2">Course</th><th class="tc2">Description</th><th class="tc3">Grade</th><th class="tc4">Year Attended</th><th class="tc5">Program Credits Earned</th></tr><tr><td class="tc11">MAST</td><td class="tc12"> 218</td><td class="tc2">Langara College 2003-05</td><td class="tc3">TRC</td><td class="tc4">2005</td><td class="tc5"> 3.00</td></tr><tr><td class="tc11">MAST</td><td class="tc12"> 234</td><td class="tc2">Langara College 2003-05</td><td class="tc3">TRC</td><td class="tc4">2005</td><td class="tc5"> 3.00</td></tr><tr><td class="tc11">MATH</td><td class="tc12"> 201</td><td class="tc2">Langara College 2003-05</td><td class="tc3">EX</td><td class="tc4">2005</td><td class="tc5"> 0.00</td></tr><tr><td class="tc11">MATH</td><td class="tc12"> 203</td><td class="tc2">Langara College 2003-05</td><td class="tc3">EX</td><td class="tc4">2005</td><td class="tc5"> 0.00</td></tr><tr><td class="tc11">MATH</td><td class="tc12"> 204</td><td class="tc2">Langara College 2003-05</td><td class="tc3">EX</td><td class="tc4">2005</td><td class="tc5"> 0.00</td></tr><tr><td class="tc11">MATH</td><td class="tc12"> 205</td><td class="tc2">Langara College 2003-05</td><td class="tc3">EX</td><td class="tc4">2005</td><td class="tc5"> 0.00</td></tr><tr><td class="tc11">MATH</td><td class="tc12"> 206</td><td class="tc2">Langara College 2003-05</td><td class="tc3">EX</td><td class="tc4">2005</td><td class="tc5"> 0.00</td></tr><tr><td class="tc11">MATH</td><td class="tc12"> 364</td><td class="tc2">Langara College 2003-05</td><td class="tc3">TRC</td><td class="tc4">2005</td><td class="tc5"> 3.00</td></tr><tr><td class="tc11">PHYS</td><td class="tc12"> 204</td><td class="tc2">Langara College 2003-05</td><td class="tc3">EX</td><td class="tc4">2005</td><td class="tc5"> 0.00</td></tr><tr><td class="tc11">PHYS</td><td class="tc12"> 224</td><td class="tc2">Langara College 2003-05</td><td class="tc3">EX</td><td class="tc4">2005</td><td class="tc5"> 0.00</td></tr></table>, <table border="0" class="crsTB"><tr><th class="c1" colspan="3">Course</th><th class="c2">Description</th><th class="c3">Attempted</th><th class="c4">Grade</th><th class="c5">Notation</th><th class="c8">GPA</th><th class="c6">Class Avg</th><th class="c7">Class Size</th><th class="c9">Program Credits Earned</th><th class="c10">Other</th></tr><tr><td class="s1">FRAN</td><td class="s2"> 305</td><td class="s3">B</td><td class="G2">COMMUNICATION ORALE</td><td class="c3"> 3.00</td><td class="c4">B+</td><td class="c5"></td><td class="c8"> 3.30</td><td class="c6"> 3.12</td><td class="c7">26</td><td class="c9"> 3.00</td><td class="c10"></td></tr><tr><td class="s1">GEOL</td><td class="s2"> 210</td><td class="s3">X</td><td class="G2">INTRODUCTION TO THE EARTH</td><td class="c3"> 3.00</td><td class="c4">A-</td><td class="c5"></td><td class="c8"> 3.70</td><td class="c6"> 3.25</td><td class="c7">69</td><td class="c9

But all this does is find the table enclosed in the `table` tag. I want to get rid of all that and have what's in the cells. 

Try Pandas next

In [2]:
col_names = ['Course', 'Num','Section',	'Description',	
             'Attempted','Grade','Notation',	
             'GPA','Class Avg',	'Class Size',	
             'Credits Earned','Other']
len(col_names)

12

In [14]:
df_list = pd.read_html('course_history.html')

files = []
for i, df in enumerate(df_list):
#     print(df)
    df.to_csv('table_{}.csv'.format(i), header=None, index=False)
    files.append('table_{}.csv'.format(i))

In [56]:
dfs_list

['df_3', 'df_4', 'df_5', 'df_6', 'df_7', 'df_8']

In [67]:
cnt = len(files)  # your loop
dict_of_df = {} # initialize empty dictionary

for i in range(3,cnt):
    dict_of_df['df_{}'.format(i)] = pd.read_csv('table_{}.csv'.format(i), skiprows=1,usecols=[0,1,2,3], names=col_names[:4])

dfs_list = list(dict_of_df.keys())
df = pd.concat(dict_of_df, ignore_index=True)
# display(df)
df.drop(columns=['Section'], inplace=True)
display(df)

           Course                         Num                   Description
0            FRAN                         305           COMMUNICATION ORALE
1            GEOL                         210     INTRODUCTION TO THE EARTH
2            MAST                         217   INTRO/MATHEMATICAL THINKING
3            MAST                         219     MULTIVARIABLE CALCULUS II
4            MECH                         211      MECHANICAL ENGR. DRAWING
5            GEOL                         208   THE EARTH, MOON AND PLANETS
6            MATH                         252             LINEAR ALGEBRA II
7            MATH                         365                   ANALYSIS II
8            STAT                         249                 PROBABILITY I
9            MATH                         366            COMPLEX ANALYSIS I
10           MATH                         369            ABSTRACT ALGEBRA I
11           MATH                         392      ELEMENTARY NUMBER THEORY
12           MATH                         475  DISCRETE DYN.SYS,CHAOS&FRACT
13  Course Topic:  DISCRETE DYNAMICAL SYSTEMS                           NaN
14           MATH                         252             LINEAR ALGEBRA II
15           MATH                         467                MEASURE THEORY
16           MATH                         470           ABSTRACT ALGEBRA II
17           MATH                         494    TOPICS/PURE & APPLIED MATH
18  Course Topic:                  SET THEORY                           NaN
19           MATH                         354            NUMERICAL ANALYSIS
20           MATH                         370  ORDINARY DIFFERENTIAL EQUAT.
21           MATH                         464                 REAL ANALYSIS
22           MATH                         494    TOPICS/PURE & APPLIED MATH
23  Course Topic:     ALGEBRAIC NUMBER THEORY                           NaN
24           INTU                        MJKY             HONOURS ALGEBRA 4
25  Course Topic:             MATH 457 MCGILL                           NaN
26           MATH                         494    TOPICS/PURE & APPLIED MATH
27  Course Topic:             RANDOM MATRICES                           NaN

In [101]:
df.info()

mask = df.Course == 'Course Topic:'
topics_ind = list(df[mask].index)
topics = list(df[mask].Num.values)

locations = list(zip(topics_ind, topics))
locations

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 3 columns):
Course         28 non-null object
Num            28 non-null object
Description    23 non-null object
dtypes: object(3)
memory usage: 752.0+ bytes

[(13, 'DISCRETE DYNAMICAL SYSTEMS'),
 (18, 'SET THEORY'),
 (23, 'ALGEBRAIC NUMBER THEORY'),
 (25, 'MATH 457 MCGILL'),
 (27, 'RANDOM MATRICES')]

In [112]:
for i in range(len(locations)):
    if i == 3:
        df.loc[locations[i][0]-1].Course = 'MATH'
        df.loc[locations[i][0]-1].Num = '457'
    else:
        df.iloc[locations[i][0]-1].Description = locations[i][1]

In [122]:
df.Num = df.Num.astype(str);
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 23 entries, 0 to 26
Data columns (total 3 columns):
Course         23 non-null object
Num            23 non-null object
Description    23 non-null object
dtypes: object(3)
memory usage: 736.0+ bytes

In [127]:
df['Course_Num'] = df['Course'] + ' ' + df['Num']
df.drop(columns=['Course', 'Num'], inplace=True)

In [130]:
df = df[['Course_Num', 'Description']]

In [140]:
df['Description'] = df['Description'].str.title()
df['Description']
df

   Course_Num                   Description
0    FRAN 305           Communication Orale
1    GEOL 210     Introduction To The Earth
2    MAST 217   Intro/Mathematical Thinking
3    MAST 219     Multivariable Calculus Ii
4    MECH 211      Mechanical Engr. Drawing
5    GEOL 208   The Earth, Moon And Planets
6    MATH 252             Linear Algebra Ii
7    MATH 365                   Analysis Ii
8    STAT 249                 Probability I
9    MATH 366            Complex Analysis I
10   MATH 369            Abstract Algebra I
11   MATH 392      Elementary Number Theory
12   MATH 475    Discrete Dynamical Systems
14   MATH 252             Linear Algebra Ii
15   MATH 467                Measure Theory
16   MATH 470           Abstract Algebra Ii
17   MATH 494                    Set Theory
19   MATH 354            Numerical Analysis
20   MATH 370  Ordinary Differential Equat.
21   MATH 464                 Real Analysis
22   MATH 494       Algebraic Number Theory
24   MATH 457             Honours Algebra 4
26   MATH 494               Random Matrices

In [141]:
df.to_csv('course_history.csv')

In [142]:
df.to_html('course_history.html')